platform :ios, '13.0'

target 'Runner' do
  use_frameworks!

  pod 'AlipaySDK', '15.8.40'
  pod 'WechatOpenSDK', '2.0.5'
  pod 'UPPaymentControl', '3.6.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'DEBUG=1',
      ]
    end
  end
end